;;;; creed.runtime.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'creed.runtime
      'creed.runtime
      (scheme#list)
      '((apply! . creed.runtime#apply!))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
