;;;; creed.builtins.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'creed.builtins
      'creed.builtins
      (scheme#list)
      '((builtins . creed.builtins#builtins))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
