;;;; creed.parser.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'creed.parser
      'creed.parser
      (scheme#list)
      '((parse . creed.parser#parse)
        (link-builtins . creed.parser#link-builtins)
        (generate-tree . creed.parser#generate-tree)
        (convert-tokens . creed.parser#convert-tokens)
        (lex . creed.parser#lex))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
