;;;; creed.types.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'creed.types
      'creed.types
      (scheme#list)
      '((make-location . creed.types#make-location)
        (location-lno . creed.types#location-lno)
        (location-lno-set! . creed.types#location-lno-set!)
        (location-cno . creed.types#location-cno)
        (location-cno-set! . creed.types#location-cno-set!)
        (location-filename . creed.types#location-filename)
        (location-filename-set! . creed.types#location-filename-set!)
        (make-token . creed.types#make-token)
        (token-value . creed.types#token-value)
        (token-value-set! . creed.types#token-value-set!)
        (token-type . creed.types#token-type)
        (token-type-set! . creed.types#token-type-set!)
        (token-location . creed.types#token-location)
        (token-location-set! . creed.types#token-location-set!)
        (make-state . creed.types#make-state)
        (state-buffer . creed.types#state-buffer)
        (state-buffer-set! . creed.types#state-buffer-set!)
        (state-mark . creed.types#state-mark)
        (state-mark-set! . creed.types#state-mark-set!)
        (state-stack . creed.types#state-stack)
        (state-stack-set! . creed.types#state-stack-set!)
        (state-symbols . creed.types#state-symbols)
        (state-symbols-set! . creed.types#state-symbols-set!)
        (make-crerror . creed.types#make-crerror))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
